### ISSUE TITLE
Update Jumuah Times

### ISSUE THREAD

**Issue by BoxlikeShowroomGloomy** [ragaeeb/das-js#289]
Update Jumu'ah Iqama Times

**Is your feature request related to a problem? Please describe.**
Iqamah times for Jumu'ah are currently inaccurate and do not reflect actual times.

**Describe the solution you'd like**
Update times to reflect 2 Jumu'ah prayers; should at least add current times (for EST):
1. 12:15 pm
1. 1:00 pm

Could also flesh out times for other months as well to include the below times (for EDT):
1. 1:00 pm
1. 1:45 pm

Additionally, could change how time for Jumu'ah are rendered to make it more clear each time for a different prayer, e.g. "Khutbah al-Jumuah #1: 12:15 PM, Kutbah al-Jumuah #2: 1:00 PM"

**Additional context**
Something like this is better than nothing:
![times](https://user-images.githubusercontent.com/75222738/100957068-d0329e00-34e7-11eb-9cae-f2413a1cb6b7.png)

**Comment by ragaeeb** [comment]
>Additionally, could change how time for Jumu'ah are rendered to make it more clear each time for a different prayer, e.g. "Khutbah al-Jumuah #1: 12:15 PM, Kutbah al-Jumuah #2: 1:00 PM"

This is a good suggestion, but from my experience there are issues getting these to look good due to mobile device sizes, they end up taking too much space with the extra characters, and thus the entire initial screen when visitors go on the page are no longer a summary of all the prayer times.

This is especially a problem on the last hour on Friday when we display the hadith which pushes the timings down. I think it'll need more thought on the UX before we get that in.
