### ISSUE TITLE
Add new lockdown post

### ISSUE THREAD

**Issue by BoxlikeShowroomGloomy** [ragaeeb/das-js#307]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Create a new blog detailing the new lockdown procedures. Do not have the exact content yet. Will update as appropriate.

**Describe alternatives you've considered**
N/A

**Additional context**
Will use the following screenshot, taken from pexels.com. Not sure if there is a better/easier way to do this...
https://images.pexels.com/photos/33041/antelope-canyon-lower-canyon-arizona.jpg

**Comment by ragaeeb** [comment]
Thanks. I'm going to make a slight change to use a different lower-resolution picture. The image you linked to is pretty hi-res, and since the image will be loaded right in the beginning of the site load, it will impact performance because the image will always load even if the user just wants to visit the site just to see the prayer times (and not scroll down to the blog posts).

I mitigated this slightly by making these images lazily load, but I fear it'll still unnecessarily take up some bandwidth due to the higher resolution image for those who many not care for it. I generally like to use lower-resolution for the thumbnail url, and if you want we can keep the higher-res one for the actual blog post when it's clicked on.
